version: '3.3'

services:
  mc:
    container_name: "mcfabric"
    image: itzg/minecraft-server
    environment:
      EULA: "true"
      TYPE: FABRIC
      VERSION: 1.18.1
      ONLINE_MODE: "false"
      MEMORY: 2300m
      TZ: Europe/Madrid 
      DIFFICULTY: hard
      VIEW_DISTANCE: 14
      MOTD: "Fabric server"
      ALLOW_FLIGHT: "true"
    ports:
      - 25566:25565
      - 25576:25575
    volumes:
      - "./server:/data"
