version: '3.3'

services:
  mc:
    container_name: "jmcfabric"
    image: itzg/minecraft-server
    environment:
      EULA: "true"
      TYPE: FABRIC
      VERSION: 1.19
      ONLINE_MODE: "false"
      MEMORY: 3000m
      TZ: Europe/Madrid 
      DIFFICULTY: hard
      VIEW_DISTANCE: 14
      MOTD: "Fabric server"
      ALLOW_FLIGHT: "true"
    ports:
      - 25565:25565
      - 25575:25575
    volumes:
      - "./server:/data"

volumes:
# Uncomment this if using the config step above
#  rclone-config:
#    external: true
  mc: {}
