version: '3.3'

services:
  mc:
    container_name: "mcfabric"
    image: itzg/minecraft-server
    environment:
      EULA: "true"
      TYPE: FABRIC
      VERSION: 1.18
      ONLINE_MODE: "false"
      MEMORY: 3500m
      TZ: Europe/Madrid 
      DIFFICULTY: hard
      VIEW_DISTANCE: 14
      MOTD: "JulenPark"
      ALLOW_FLIGHT: "true"
    ports:
      - 25565:25565
      - 25575:25575
    volumes:
      - "~/minecraft-server/server:/data"
