version: '3.3'

services:
  mc:
    container_name: "jmcfabric"
    image: itzg/minecraft-server
    environment:
      EULA: "true"
      TYPE: FABRIC
      VERSION: 1.18.1
      ONLINE_MODE: "false"
      MEMORY: 2300m
      TZ: Europe/Madrid 
      DIFFICULTY: hard
      VIEW_DISTANCE: 14
      MOTD: "Fabric server"
      ALLOW_FLIGHT: "true"
    ports:
      - 25566:25565
      - 25576:25575
    volumes:
      - "./server:/data"

  backup:
    container_name: "jmcbackup"
    image: itzg/mc-backup
    environment:
      RCON_HOST: mc
      BACKUP_METHOD: tar
      DEST_DIR: /backups
      #RESTIC_PASSWORD: password
      #RESTIC_REPOSITORY: rclone:drive:minecraft
      #RCON_PORT: 25576
      #SERVER_PORT: 25566
    volumes:
      # mount volume pre-configured using a host mounted file
      - ./rclone.conf:/config/rclone/rclone.conf
      # or configure one into a named volume using
      # docker run -it --rm -v rclone-config:/config/rclone rclone/rclone config
      # and change the above to
      # - rclone-config:/config/rclone
      - mc:/data:ro
      - "./backups:/backup"
    network_mode: "service:mc"

volumes:
# Uncomment this if using the config step above
#  rclone-config:
#    external: true
  mc: {}
  backups: {}
